kind: project
metadata:
  name: git-proj-vivek
spec:
  description: my new project
  functions:
  - name: myjob
    kind: job
    image: mlrun/mlrun
    handler: training.train_ad_model
    with_repo: true
  - url: serving.yaml
    name: serving
    with_repo: true
  workflows: []
  artifacts: []
  source: ''
  desired_state: online
